### ISSUE TITLE
Catalog Proposal

### ISSUE THREAD

**Issue by honwen** [compassd/configs#1]
- `base`: like *default.json*
- `dispatch-base`: like *example.yaml*
- `dispatch-whitelist`: like *success_rule.json*
- `dispatch-blacklist`: TODO
- `dispatch-hyper`: like *example_full.yaml*

**Comment by honwen** [comment]
- `cache`: like *query_cache_policy.yaml*
- `zone`: like *success_zone.yaml*

**Comment by LEXUGE** [comment]
I am not sure about the catalog actually. Current scheme is that any configs (`*.yaml`, `*.yml`, `*.json`) under `configs/` will be **recursively** found out and checked by dcompass-maxmind.
